name: Generate animation

on:
  schedule:
    - cron: "0 */6 * * *" 
  workflow_dispatch:
  push:
    branches:
    - master


jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake-animation.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/snake-animation.svg

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Push snake-animation.svg to the output branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: animation-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}